server/domain/build.gradle, server/settings.gradle, server/src/main/java/com/fittogether/server/FitTogetherApplication.java, server/src/main/resources/application.properties
Changes
---
- build.gradle 수정
- application.properties 추가
- domain 모듈 추가
=> setting: [all] - 프로젝트 세팅

server/build.gradle
Changes
---
- build.gradle 수정: 하위모듈의 build.gradle인식을 못함
=> setting: [server] - build.gradle 수정

server/video/build.gradle
plugins에
id 'io.spring.dependency-management' version '1.0.15.RELEASE'
id 'org.springframework.boot' version '2.6.3'
추가
=> Setting: [video] build gradle

server/domain/src/main/java/com/fittogether/server/domain/token/AES256Utils.java, server/domain/src/main/java/com/fittogether/server/domain/token/JwtConfig.java, server/domain/src/main/java/com/fittogether/server/domain/token/JwtProvider.java, server/domain/src/main/java/com/fittogether/server/domain/token/UserVo.java
Changes
---
- 토큰 생성 기능 추가
- 토큰 유효검사 기능 추가
- jwt configuration 추가: 다른 모든 모듈이 token 사용 예정
TODO
---
- 다른 모듈: token 관련된 작업 사용 -> domain 의존성 추가 필요
=> feat: [domain] - 토큰

server/build.gradle, server/src/main/java/com/fittogether/server/SwaggerConfig.java
Changes
---
- 이전 각 모듈의 package 인식 안됨 -> 각 모듈들 의존성 추가
- SwaggerConfig 추가
=> settings: [setting] - package 인식 해결

server/posts/src/main/java/com/fittogether/server/posts/Main.java, server/posts/src/main/java/com/fittogether/server/posts/controller/PostController.java, server/posts/src/main/java/com/fittogether/server/posts/domain/dto/AddPostForm.java, server/posts/src/main/java/com/fittogether/server/posts/domain/dto/PostDto.java, server/posts/src/main/java/com/fittogether/server/posts/domain/model/Hashtag.java, server/posts/src/main/java/com/fittogether/server/posts/domain/model/Post.java, server/posts/src/main/java/com/fittogether/server/posts/domain/model/PostHashtag.java, server/posts/src/main/java/com/fittogether/server/posts/domain/repository/HashtagRepository.java, server/posts/src/main/java/com/fittogether/server/posts/domain/repository/PostHashtagRepository.java, server/posts/src/main/java/com/fittogether/server/posts/domain/repository/PostRepository.java, server/posts/src/main/java/com/fittogether/server/posts/service/PostService.java, server/posts/src/test/http/posts.http, server/user/src/main/java/com/fittogether/server/user/type/Category.java
- 게시글 작성
- 해시태그 구현
토큰 부분은 일단 주석 처리하고 구현했습니다.
=> Feat : [posts] - 게시글 작성 및 해시태그 구현

web/src/components/common/Footer.tsx
=> feat:[feature/Footer]-푸터 마크업

web/src/components/ExerciseInfo/VideoList.tsx, web/src/components/ExerciseInfo/VideoPopup.tsx, web/src/components/ExerciseInfo/YoutubeApi.tsx
=> feat:[feature/VideoList]-운동정보 페이지 마크업

web/src/components/Bookmark/BookmarkFolder.tsx, web/src/components/Bookmark/BookmarkSetting.tsx, web/src/components/Bookmark_MyVideos/MyVideoList.tsx, web/src/pages/Bookmark/Bookmark.tsx, web/src/pages/BookmarkSub/MyVideos.tsx
=> Bookmark 레이아웃

server/user/src/main/java/com/fittogether/server/user/controller/UserController.java, server/user/src/main/java/com/fittogether/server/user/domain/dto/SignInForm.java, server/user/src/main/java/com/fittogether/server/user/domain/dto/UserType.java, server/user/src/main/java/com/fittogether/server/user/domain/model/User.java, server/user/src/main/java/com/fittogether/server/user/domain/repository/UserRepository.java, server/user/src/main/java/com/fittogether/server/user/exception/UserErrorCode.java, server/user/src/main/java/com/fittogether/server/user/exception/UserExceptionAdvice.java, server/user/src/main/java/com/fittogether/server/user/service/KakaoSignInService.java, server/user/src/main/java/com/fittogether/server/user/service/UserSignInService.java, server/user/src/main/resources/application-user.properties, server/user/src/test/java/userTest.http
Changes
---
- 일반 로그인 기능 구현
- 카카오 로그인 구현
- http 테스트 코드 추가
=> feat: [user] - 로그인 구현 및 테스트코드

server/posts/src/main/java/com/fittogether/server/posts/controller/PostController.java, server/posts/src/main/java/com/fittogether/server/posts/domain/model/Post.java, server/posts/src/main/java/com/fittogether/server/posts/service/PostService.java, server/posts/src/test/http/posts.http
- 게시판 삭제 기능
PostHashtag가 연결되어 있기 때문에 해당 postId의 postHashtag를 먼저 삭제 후 게시글을 삭제하도록 구현했습니다.
=> Feat : [posts] - 게시글 삭제 구현

server/user/src/main/java/com/fittogether/server/user/controller/UserInfoController.java, server/user/src/main/java/com/fittogether/server/user/domain/dto/ExerciseType.java, server/user/src/main/java/com/fittogether/server/user/domain/dto/UpdateUserForm.java, server/user/src/main/java/com/fittogether/server/user/domain/dto/UserDto.java, server/user/src/main/java/com/fittogether/server/user/domain/model/User.java, server/user/src/main/java/com/fittogether/server/user/domain/repository/UserRepository.java, server/user/src/main/java/com/fittogether/server/user/exception/UserErrorCode.java, server/user/src/main/java/com/fittogether/server/user/service/UserService.java, server/user/src/main/java/com/fittogether/server/user/service/UserSignInService.java, server/user/src/test/java/userTest.http
- `put`: /users/my
- `header`: token
- `body`: updateform
- user의 exercise 속성: string -> list
- list형의 데이터를 문자열로 저장하면 데이터를 검색하기 어려울 뿐 아니라, 데이터정규화(중복)를 위반한 것
=> feat: [user] - 회원정보 수정

server/video/build.gradle, server/video/src/main/java/com/fittogether/server/video/controller/PlaylistController.java, server/video/src/main/java/com/fittogether/server/video/domain/form/PlaylistForm.java, server/video/src/main/java/com/fittogether/server/video/domain/model/BaseEntity.java, server/video/src/main/java/com/fittogether/server/video/domain/model/Playlist.java, server/video/src/main/java/com/fittogether/server/video/domain/repository/PlaylistRepository.java, server/video/src/main/java/com/fittogether/server/video/exception/VideoCustomException.java, server/video/src/main/java/com/fittogether/server/video/exception/VideoErrorCode.java, server/video/src/main/java/com/fittogether/server/video/exception/VideoExceptionController.java, server/video/src/main/java/com/fittogether/server/video/service/PlaylistService.java, server/video/src/main/java/com/fittogether/server/video/test.java, server/video/src/test/java/com/fittogether/server/video/service/PlaylistServiceTest.java
Changes
---
* PlaylistForm을 통해 playlist 생성 기능 구현
* playlist 생성 시 userId와 playlistName을 통해 존재 여부 확인 후 생성
* 이미 존재하는 playlist에 대한 에러 처리 구현
* 간단한 테스트 코드 구현
Todo
---
* 로그인 한 사용자의 userId를 저장하도록 구현할 예정 (Jwt 토큰 사용)
* 테스트 코드 보강
* playlist 조회, 수정, 삭제 기능 추가
=> Feat: [video] - "플레이리스트 생성 기능 구현"

web/src/components/Messenger/ChatList.tsx, web/src/components/Post/PostContents.tsx, web/src/components/common/MateList.tsx, web/src/components/common/MateListitem.tsx
Messenger관련 컴포넌트와 MateList.tsx, MateListItem.tsx
=> feat: [feature/Messenger] - MateList 컴포넌트 구현

web/src/components/common/ScrollTopButton.tsx
feature/ScrollTopButton PR! merge 요청!
=> feat:[feature/ScrollTopButton]-ScrollTopButton 브랜치 생성 및 수정

web/src/pages/MainPage.tsx
feature/MainPage PR! merge 요청!
=> feat:[feature/MainPage]-MainPage 브랜치 생성 및 수정

server/video/src/main/java/com/fittogether/server/video/controller/PlaylistController.java, server/video/src/main/java/com/fittogether/server/video/domain/dto/PlaylistDto.java, server/video/src/main/java/com/fittogether/server/video/service/PlaylistService.java
Changes
---
* token으로 user의 userId에 해당하는 Playlist를 PlaylistDto 리스트로 반환
* 기존에 PlaylistController에서 Playlist 엔티티로 반환하는 코드를 PlaylistDto로 반환하도록 변경
Todo
---
* 플레이리스트 삭제, 수정 기능 추가
=> Feat: [video] - "플레이리스트 조회 기능 추가"

server/video/src/main/java/com/fittogether/server/video/controller/PlaylistController.java
Changes
---
* 기존 createPlaylist 작업 완료 후 PlaylistDto로 결과값 반환하는 것을 작업 완료 상태코드(HttpStatus.CREATED)와 메세지만 보내는 것으로 바꿈
=> Refactor: [video] - "PlaylistController 반환할때 ResponseEntity 구조 변경"

server/dm/src/main/java/com/fittogether/server/dm/domain/dto/RequestListDto.java, server/dm/src/main/java/com/fittogether/server/dm/domain/repository/RequestRepository.java, server/dm/src/main/java/com/fittogether/server/dm/mate/controller/MateController.java, server/dm/src/main/java/com/fittogether/server/dm/service/MateService.java
유저 토큰을 받아와 로그인 사용자를 인증한후 
사용자가 메이트 요청을 보냈던 목록들을 상대방의 수락 여부의 상관없이 모두 List으로 반환합니다
ReuqestListDto를 별도로 작성했습니다.
=> Feat/[dm] - 나의 메이트 요청 리스트 조회

server/user/src/main/java/com/fittogether/server/user/controller/LocationController.java, server/user/src/main/java/com/fittogether/server/user/domain/dto/LocationDto.java, server/user/src/main/java/com/fittogether/server/user/service/LocationService.java
- `put`: /location?lat={lat}&long={long}
- `header`: token
- return : {"status": "success", "message": "나의 위치 업데이트 완료"}
=> feat: [user] - 현재 나의 위치 업데이트

server/video/src/main/java/com/fittogether/server/video/controller/PlaylistController.java, server/video/src/main/java/com/fittogether/server/video/domain/model/Playlist.java, server/video/src/main/java/com/fittogether/server/video/domain/repository/PlaylistRepository.java, server/video/src/main/java/com/fittogether/server/video/exception/VideoErrorCode.java, server/video/src/main/java/com/fittogether/server/video/service/PlaylistService.java
Changes
---
* PlaylistForm을 통해 바꾸고자 하는 이름을 받음
* 변경하고자 하는 이름이 기존 Playlist 이름과 같은지 확인 후 같으면 에러 처리, 다르면 변경
* 삭제하고자 하는 이름의 Playlist가 존재하는지 확인 후 존재하지 않으면 에러 처리, 존재하면 해당 이름의 Playlist 삭제
=> Feat: [video] - "플레이리스트 이름 변경 기능 및 삭제 기능 추가"

server/dm/src/main/java/com/fittogether/server/dm/domain/entity/Request.java, server/dm/src/main/java/com/fittogether/server/dm/service/MateService.java
=> Feat/[dm] - request (요청 에러수정) 

web/src/components/Messenger/ChatList.tsx
=> feat:[feature/Header]-Header브랜치 생성

server/domain/build.gradle, server/domain/src/main/java/com/fittogether/server/domain/token/JwtProvider.java
##Changes
- 토큰이 레디스에 24시간 유효하도록
- 로그아웃시, 해당 토큰은 레디스에서 삭제
=> feat: [domain] - 토큰을 레디스에 저장

server/user/src/main/java/com/fittogether/server/user/controller/UserController.java, server/user/src/main/java/com/fittogether/server/user/exception/UserErrorCode.java, server/user/src/main/java/com/fittogether/server/user/service/UserSignInService.java
- `post`: http://localhost:8080/users/signout
- `header`: String token
- `contents` : 로그아웃시, 레디스의 해당 토큰을 삭제
- redisTemplate으로 해당 데이터의 유효기간을 정할 수 있다.
=> feat: [user] - 로그아웃

server/video/src/main/java/com/fittogether/server/video/controller/VideoController.java, server/video/src/main/java/com/fittogether/server/video/domain/repository/PlaylistVideoRepository.java, server/video/src/main/java/com/fittogether/server/video/service/VideoService.java
Changes
---
* header로 토큰을 받고 사용자 검증
* pathVariable로 video조회할 playlist 이름 받음
* playlist 이름과 userId로 해당 playlist 가져옴
* 가져온 playlist의 id로 playlist와 video 관계테이블에서 데이터 가져온 후 playlist 이름과 video 제목 반환
=> Feat: [video] - "플레이리스트에 있는 동영상 조회"

web/src/components/common/Footer.tsx
=> feat:[feature/Footer]-footer조금 수정함

server/video/src/main/java/com/fittogether/server/video/controller/VideoController.java, server/video/src/main/java/com/fittogether/server/video/domain/repository/PlaylistVideoRepository.java, server/video/src/main/java/com/fittogether/server/video/exception/VideoErrorCode.java, server/video/src/main/java/com/fittogether/server/video/service/VideoService.java
Changes
---
* `delete`: http://localhost:8080/playlist/{name}/video/{videoId}
* `header`: String token
Content
---
* 플레이리스트에서 삭제할 동영상의 정보를 pathVariable을 통해 playlistName과 videoId으로 받음
* 존재하지 않는 playlistName이면 에러 처리
* 존재하지 않는 videoId면 에러 처리
* playlistName과 videoId에 해당하는 데이터를 playlistVideo db에서 삭제
=> Feat: [video] - "플레이리스트 내 동영상 삭제"

server/dm/src/main/java/com/fittogether/server/dm/domain/dto/RequestDto.java, server/dm/src/main/java/com/fittogether/server/dm/domain/entity/Request.java, server/dm/src/main/java/com/fittogether/server/dm/domain/repository/RequestRepository.java, server/dm/src/main/java/com/fittogether/server/dm/mate/controller/MateController.java, server/dm/src/main/java/com/fittogether/server/dm/service/MateService.java
기존의 메이트 요청 , 수락 부분을  멘토님 피드백 반영(dto통합, stream사용) , 요청값 user_id -> nickname으로 변경
=> fix:[dm]-메이트 요청 , 수락 (dto통합 ,stream사용,요청값 nickname사용)

server/user/src/main/java/com/fittogether/server/user/controller/UserInfoController.java, server/user/src/main/java/com/fittogether/server/user/domain/dto/UpdateUserForm.java, server/user/src/main/java/com/fittogether/server/user/domain/dto/UpdateUserPassword.java, server/user/src/main/java/com/fittogether/server/user/domain/repository/UserRepository.java, server/user/src/main/java/com/fittogether/server/user/exception/UserErrorCode.java, server/user/src/main/java/com/fittogether/server/user/service/UserService.java, server/user/src/main/java/com/fittogether/server/user/service/UserSignInService.java, server/user/src/main/java/com/fittogether/server/user/service/UserSignUpService.java
1. [프론트요청] 회원정보수정에서의 비밀번호 변경 uri 분리
- `put` : /user/my/password
- `header` : String token
- `body` : UpdateUserPassword(String pw)
- `return` : UserDto
2. 비밀번호 암호화시켜서 회원가입 및 로그인 하도록 구현
- AES256 이용하여 암호화
- 비밀번호 같은 중요한 정보는 해당 서버 개발자도 파악할 수 없도록 구현하여 보안 강화
- merge 후, drop user table and create user table. 왜냐하면 로그인할 때도 암호화시킨 코드로 동작되기 때문에 이전 데이터들 초기화.
=> add: [user] - 비밀번호

server/posts/src/main/java/com/fittogether/server/posts/controller/ReplyController.java, server/posts/src/main/java/com/fittogether/server/posts/domain/dto/ReplyDto.java, server/posts/src/main/java/com/fittogether/server/posts/service/ReplyService.java
대댓글 삭제시 childReplyId가 반환되지 않는 부분 수정
=> refactor : [posts] - 오류 수정

server/user/src/main/java/com/fittogether/server/user/controller/UserController.java
- `request method` : get -> post
(처음 카카오 로그인하는 사용자라면 회원가입도 진행하기 때문에)
=> fix: [user] - 카카오 로그인

web/src/components/Sign/KakaoAuth.tsx, web/src/components/Sign/SignUpSetting.tsx
-카카오 로그인 로직을 수정하였습니다.
-아이디 유효성 조건을 강화하였습니다.
=> fix[카카오 로그인 수정, 아이디 유효성검사 강화]

web/src/components/Bookmark/BookmarkFolder.tsx, web/src/components/Bookmark/BookmarkSetting.tsx, web/src/components/MyVideos/MyVideoList.tsx, web/src/pages/Bookmark.tsx, web/src/pages/MyVideos.tsx
-서버에서 불러온 유저가 저장한 재생 목록이 보여지게 수정하였습니다.
-재생 목록의 썸네일을 누르면 해당 재생 목록의 상세 페이지로 이동하게 수정하였습니다.
=> feat[Bookmark 수정]

server/posts/src/main/java/com/fittogether/server/posts/controller/SearchController.java, server/posts/src/main/java/com/fittogether/server/posts/domain/dto/PostListDto.java, server/posts/src/main/java/com/fittogether/server/posts/domain/repository/PostHashtagRepository.java, server/posts/src/main/java/com/fittogether/server/posts/domain/repository/PostRepository.java, server/posts/src/main/java/com/fittogether/server/posts/service/SearchService.java
검색 및 전체 게시글 기능에 size와 page 받아와서 페이지 네이션 기능 추가,
검색의 반환 값으로 해시태그 추가
=> refactor : [posts] - 게시글 검색 페이지네이션 추가

server/user/src/main/java/com/fittogether/server/user/service/LocationService.java
- 기존: 3km 내 사용자 조회시, 현재 로그인 한 사용자 포함하여 반환
- 수정: 3km 내 사용자 조회에서 현재 로그인 한 사용자는 제외하여 반환
=> add: [user] - 3km 내 사용자 조회

web/src/components/FindMate/Map.tsx, web/src/components/FindMate/UserProfile.tsx
=> feat: [feature/findMate] - 위치 검색 기능 추가

server/posts/src/main/java/com/fittogether/server/posts/controller/SearchController.java, server/posts/src/main/java/com/fittogether/server/posts/domain/dto/PostResponse.java, server/posts/src/main/java/com/fittogether/server/posts/exception/ErrorCode.java, server/posts/src/main/java/com/fittogether/server/posts/service/ReplyService.java, server/posts/src/main/java/com/fittogether/server/posts/service/SearchService.java
전체 게시글 및 게시글 검색 시 반환값으로 전체 게시글 수 반환 추가,
수정, 삭제 시 ErrorCode 통일
=> refactor : [posts] - 게시글 검색 시 반환 값 변경

web/src/App.tsx, web/src/components/MyPage/MyPostList.tsx, web/src/components/Post/PostContents.tsx, web/src/components/Posts/PostFilter.tsx, web/src/components/Posts/PostList.tsx, web/src/components/common/Header.tsx, web/src/components/common/PostListItem.tsx, web/src/pages/Posts.tsx, web/src/recoil/posts/atoms.ts
페이지네이션 방식 변경
전체 postList를 가져와 프론트에서 잘라서 쓰는 방식에서 원하는 post 갯수만큼 백엔드로 요청하는 방식으로 변경
=> feat: [feature/community] - 페이지네이션 방식 변경

web/src/components/common/AlertList.tsx, web/src/components/common/AlertListItem.tsx, web/src/components/common/MateRequest.tsx
1. 메이트 요청 창에서 수락 버튼 누를 경우 서버로 수락했음을 전달
- 요청을 보낸 사람의 ID(알림 구현 후 수정 필요) 및 요청을 받은 사람의 token을 담아서.
2. 거절 버튼 누를 경우 아무런 통신도 일어나지 않고 그냥 창 종료
=> feat[메이트요청 수락 서버에 전달]

server/notification/build.gradle
=> feat: [notification] - build.gradle 추가

web/src/components/Sign/FindUserPassword.tsx
1. status: 200 → "해당 이메일로 임시 비밀번호를 전송하였습니다."
2. status: 400 → "일치하는 회원이 없습니다."
3. 그 외 → "알 수 없는 오류가 발생했습니다." / "서버 요청 중 오류가 발생했습니다."
=> feat[비밀번호 찾기 요청 시 응답에 따른 메세지 출력]

server/posts/build.gradle, server/posts/src/main/java/com/fittogether/server/posts/service/LikeService.java, server/posts/src/main/java/com/fittogether/server/posts/service/ReplyService.java
notification 모듈 의존성 추가
아요, 댓글, 대댓글 작성 시
notificationService에서 createNotification 을 불러와 
user.getNickname으로 보내는 사람 닉네임,
post.getUser.getUserId()로 알람을 보낼 사람, 
(  대댓글은 postReply.getUser.getUserId()  )
알람타입, 
요청url을 보내는 알람기능 추가.
=> Refactor : [posts] -  알람기능 추가

server/dm/build.gradle, server/dm/src/main/java/com/fittogether/server/dm/service/MateService.java
=> add/dm - 메이트 요청 알림기능

server/posts/src/main/java/com/fittogether/server/posts/service/LikeService.java, server/posts/src/main/java/com/fittogether/server/posts/service/PostService.java, server/posts/src/main/java/com/fittogether/server/posts/service/SearchService.java
전체 게시글 및 검색 시 좋아요도 실시간 업데이트가 되지 않는 문제점
>>
조회수와 마찬가지로 캐시값 가져와서 반영되도록 수정하였습니다.
=> refactor : [posts] - 전체 게시글 및 검색 시 좋아요 업데이트 수정

web/src/App.tsx, web/src/components/Sign/SignInSetting.tsx, web/src/components/common/Header.tsx
로그아웃 후 토큰이 없는데도 SSE 연결 시도 -> 로그아웃 후 새로고침을 하여 시도하지 않도록 변경
=> feat[로그아웃 후 새로고침]

web/src/components/Messenger/ChatApp.tsx
=> feat:[feature/Messenger]-웹소켓 메세지 조회 불러오기
